appiumURL=http://0.0.0.0:
androidAutomationName=uiautomator2
androidAppPackage=com.swaglabsmobileapp
androidAppActivity=com.swaglabsmobileapp.MainActivity
androidAppLocation=/app/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk
iOSAutomationName=XCUITest
iOSBundleID=com.saucelabs.SwagLabsMobileApp
iOSAppLocation=/app/iOS.Simulator.SauceLabs.Mobile.Sample.app.2.7.1.app
iOSAppLocationReal=/app/iOS.RealDevice.SauceLabs.Mobile.Sample.app.2.7.1.ipa