#extent.properties
#For which reporter need to be enabled
#Enable the spark for latest version
extent.reporter.spark.start=true

#providng the path to the reporter config XML file
#Need to create such xml file into root folder
extent.reporter.spark.config=spark-config.xml

#Providing the path where the report will be generated
#Generting into root folder
extent.reporter.spark.out=ExtentSpark.html